
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>about</title>
</head>
<body>
	<a href="index.php">Back</a>
<p>It usually has four wheels and an internal combustion engine fueled most often by gasoline, a liquid petroleum product. Known more commonly as a car, formerly as a motorcar, it is one of the most universal of modern technologies, manufactured by one of the world's largest industries.</p>

<h2>Another</h2>
<p>A car, or an automobile, is a motor vehicle with wheels. Most definitions of cars state that they run primarily on roads, seat one to eight people, have four wheels, and mainly transport people, not cargo.[1][2]

French inventor Nicolas-Joseph </P>

<P>Cugnot built the first steam-powered road vehicle in 1769, while French-born Swiss inventor François Isaac de Rivaz designed and constructed the first internal combustion-powered automobile in 1808. The modern car—a practical, marketable automobile for everyday use—was invented in 1886, when German inventor Carl Benz patented his Benz Patent-Motorwagen. </P>\
<p>
Commercial cars became widely available during the 20th century. One of the first cars affordable by the masses was the 1908 Model T, </p>
<p>an American car manufactured by the Ford Motor Company. Cars were rapidly adopted in the US, where they replaced horse-drawn carriages.[3] In Europe and other parts of the world, demand for automobiles did not increase until after World War II.[4] The car is considered an essential part of the developed economy.</p>
</body>
</html>