
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link rel="stylesheet" type="text/css" href="css.css">
</head>
<body>

<div class="container">

	<div class="card">
		<img src="vehicleimages/everest 5.jpg"alt="Cheetah">
		<div class="intro">
			<h1><a class="login"href="LOGIN.PHP">Login</a></h1>
			        <p>
				    <span>
					<a class="login"href="SIGNUP.php">Register</a>
			        </span>Please click here </p>
                    </div>
	                </div>
                    </div>
		
<div class="container">
	<div class="card">
		<img src="vehicleimages/exterior_2L_1.jpg"alt="Cheetah">
		<div class="intro">
				<h1>ISUZU</h1>
			<p>Lah@<span>
				Isuzu
			</span
			> Isuzu is a Japanese multinational automobile manufacturer headquartered in Yokohama</p>
			
		</div>

	</div>
</div>
<div class="container">
	<div class="card">
		<img src="vehicleimages/IMG_7407.jpg"alt="Cheetah">
		<div class="intro">
		<h1>Toyota Fortuner</h1>
			<p>Lah@<span>
                Toyota Fortuner
                  </span> also known as the Toyota SW4, is a mid-size SUV manufactured by the Japanese automaker Toyota since 2004</p>
		</div>
	</div>
</div>

</body>
</html>